{{- if (include "srcds.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  steam.user: {{ .Values.steam.user | b64enc | quote }}
  steam.pass: {{ .Values.steam.pass | b64enc | quote }}
  steam.auth: {{ .Values.steam.auth | b64enc | quote }}
  srcds.rcon.password: {{ randAlphaNum 16 | b64enc | quote }}
  srcds.password: {{ randAlphaNum 16 | b64enc | quote }}
  srcds.gslt: {{ .Values.srcds.gslt | b64enc | quote }}
{{- end -}}
